'use strict';
const canvas=document.getElementById('field'),stage=document.getElementById('stage'),slider=document.getElementById('slider'),play=document.getElementById('play');
const state={catalog:null,data:null,timer:0,last:0,playhead:0,duration:420,scene:null};
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function clock(value){const seconds=Math.max(0,Math.ceil(value));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function updateStats(stats){document.getElementById('time').textContent=`${stats.time.toFixed(1)} s`;document.getElementById('elapsed').value=`${stats.time.toFixed(1)} s`;document.getElementById('alive').textContent=`${stats.alive} / ${stats.total}`;document.getElementById('attacks').textContent=stats.attacks;document.getElementById('coverage').textContent=`${stats.telemetryStart.toFixed(0)}–${stats.telemetryEnd.toFixed(0)} s`;document.getElementById('camera').textContent=stats.camera;document.getElementById('clock').value=clock(stats.remaining)}
state.scene=BattleScopeArena3D.create({canvas,stage,data:null,fieldImage:'field.jpg',getTime:()=>Number(slider.value),onStats:updateStats});
function stop(){cancelAnimationFrame(state.timer);state.timer=0;play.textContent='播放'}
function toggle(){if(state.timer){stop();return}state.last=performance.now();state.playhead=Number(slider.value);if(state.playhead>=state.duration)state.playhead=0;play.textContent='暂停';const tick=now=>{const elapsed=(now-state.last)/1000;state.last=now;state.playhead+=elapsed;if(state.playhead>state.duration)state.playhead=state.playhead%state.duration;slider.value=state.playhead;state.timer=requestAnimationFrame(tick)};state.timer=requestAnimationFrame(tick)}
async function select(game,button){stop();document.querySelectorAll('.game').forEach(el=>el.setAttribute('aria-pressed',String(el===button)));document.getElementById('title').textContent='正在加载…';const response=await fetch(game.data);if(!response.ok)throw Error(`回放读取失败 (${response.status})`);state.data=await response.json();state.duration=Number(state.data.round?.duration_seconds)||BattleScopeArena3D.officialArena.roundDuration;slider.min=0;slider.max=state.duration;slider.step=.01;slider.value=0;state.playhead=0;slider.disabled=false;play.disabled=false;document.getElementById('title').textContent=`${game.red_school} vs ${game.blue_school}`;state.scene.setData(state.data)}
function drawCatalog(games){const root=document.getElementById('catalog');root.innerHTML=games.length?games.map((game,index)=>`<button class="game" type="button" data-index="${index}" aria-pressed="false"><strong>M${String(game.match_number).padStart(3,'0')} · G${game.round}</strong><small>${esc(game.red_school)} vs ${esc(game.blue_school)}</small><small>${esc(game.region)} · ${esc(game.started_at)}</small></button>`).join(''):'<div class="empty">当前仓库尚未生成三维数据。请在 battlescope 数据仓库中运行静态导出脚本。</div>';root.querySelectorAll('.game').forEach(button=>button.addEventListener('click',()=>select(games[Number(button.dataset.index)],button).catch(error=>{document.getElementById('title').textContent=error.message})))}
fetch('catalog.json').then(response=>{if(!response.ok)throw Error('目录读取失败');return response.json()}).then(payload=>{state.catalog=payload;const strong=payload.scope.strong_schools.join('、');document.getElementById('scope').textContent=`官网范围：复旦大学全部对局，以及强校分析名单（${strong}）任一方参赛的对局，共 ${payload.game_count} 局。`;drawCatalog(payload.games)}).catch(error=>document.getElementById('catalog').innerHTML=`<div class="empty">${esc(error.message)}</div>`);
document.getElementById('search').addEventListener('input',event=>{if(!state.catalog)return;const query=event.target.value.trim().toLocaleLowerCase('zh-CN');drawCatalog(state.catalog.games.filter(game=>[game.red_school,game.blue_school,game.region,game.schedule,`M${game.match_number}`,`G${game.round}`].join(' ').toLocaleLowerCase('zh-CN').includes(query)))});
slider.addEventListener('input',()=>{stop();state.playhead=Number(slider.value);state.scene.render()});play.addEventListener('click',toggle);document.getElementById('reset').addEventListener('click',()=>state.scene.setView('tactical'));document.getElementById('top').addEventListener('click',()=>state.scene.setView('top'));document.getElementById('low').addEventListener('click',()=>state.scene.setView('low'));
